### ISSUE TITLE
mod files compilation error

### ISSUE THREAD

**Issue by RichaS19** [LFPy/LFPy#285]
Does LFPy 2.1.1/2.1.2 require MacOSX10.15 or a higher version of Mac? I couldn't get the mod files to compile, because it showed an error; please see the attachment. 
Could you let me know if the system's version is also one of the requirements? or is it not working well with neuron 7.8?

![Screen Shot 2020-12-04 at 12 04 18 pm](https://user-images.githubusercontent.com/75294807/101131190-e39a5200-362a-11eb-8757-f70acb3e7a23.png)

**Comment by espenhgn** [comment]
Hi again, @RichaS19. Nothing in LFPy should really be specific to any macos10.x version. This error occurs as the LFPy installer try and compile a Neuron NMODL file https://raw.githubusercontent.com/LFPy/LFPy/master/LFPy/test/expsyni.mod using the Neuron supplied script "nrnivmodl", but fails because of a missing libreadline in XCode. You can download that file to a separate folder and run `nrnivmodl` in that folder and get the same error I presume. Check that your XCode version is correct/up to date, and if you still encounter problems it is better if you post to the Neuron developers directly at https://github.com/neuronsimulator/nrn/issues (but check that a similar issue has not been raised already)

**Comment by RichaS19** [comment]
> Hi again, @RichaS19. Nothing in LFPy should really be specific to any macos10.x version. This error occurs as the LFPy installer try and compile a Neuron NMODL file https://raw.githubusercontent.com/LFPy/LFPy/master/LFPy/test/expsyni.mod using the Neuron supplied script "nrnivmodl", but fails because of a missing libreadline in XCode. You can download that file to a separate folder and run `nrnivmodl` in that folder and get the same error I presume. Check that your XCode version is correct/up to date, and if you still encounter problems it is better if you post to the Neuron developers directly at https://github.com/neuronsimulator/nrn/issues (but check that a similar issue has not been raised already)

Hello! yes updating command-line tools for XCode fixed the compilation issue. Thank you so much!
